const quiz = [
  { q: 'Which city is known as the “City of Victory” and has a UNESCO World Heritage monument?', a: ['Gwalior', 'Hampi', 'Jaipur'], correct: 1 },
  { q: 'What does heritage conservation protect for future generations?', a: ['Only old buildings', 'Culture, stories, and landmarks', 'Tourist tickets'], correct: 1 },
  { q: 'Which action supports heritage preservation?', a: ['Respecting monuments and sharing knowledge', 'Writing on historic walls', 'Ignoring local history'], correct: 0 }
];
let quizIndex = 0, quizScore = 0;
const renderQuiz = () => {
  const item = quiz[quizIndex];
  document.querySelector('#quiz-progress').textContent = `Question ${quizIndex + 1} of ${quiz.length}`;
  document.querySelector('#quiz-question').textContent = item.q;
  const answers = document.querySelector('#quiz-answers'); answers.innerHTML = '';
  item.a.forEach((answer, index) => { const b = document.createElement('button'); b.textContent = answer; b.onclick = () => answerQuiz(index); answers.appendChild(b); });
};
const answerQuiz = index => { const item = quiz[quizIndex]; if (index === item.correct) quizScore++; quizIndex++; const message = document.querySelector('#quiz-message'); if (quizIndex < quiz.length) { message.textContent = index === item.correct ? 'Correct! Keep going.' : 'Nice try—keep exploring.'; renderQuiz(); } else { document.querySelector('#quiz-progress').textContent = 'Complete'; document.querySelector('#quiz-question').textContent = `You scored ${quizScore} / ${quiz.length}`; document.querySelector('#quiz-answers').innerHTML = ''; message.textContent = 'Heritage stays alive when we learn, share, and care for it.'; document.querySelector('#quiz-restart').hidden = false; } };
document.querySelector('#quiz-restart').onclick = () => { quizIndex = quizScore = 0; document.querySelector('#quiz-restart').hidden = true; document.querySelector('#quiz-message').textContent = ''; renderQuiz(); }; renderQuiz();

const waste = [{e:'🥤',n:'Plastic bottle',b:'recycle'},{e:'🍌',n:'Banana peel',b:'compost'},{e:'🧻',n:'Used tissue',b:'landfill'},{e:'📦',n:'Cardboard box',b:'recycle'},{e:'🍂',n:'Dry leaves',b:'compost'}]; let wasteIndex=0,wasteScore=0;
function renderWaste(){const x=waste[wasteIndex]; document.querySelector('#eco-emoji').textContent=x.e;document.querySelector('#eco-item').textContent=x.n;document.querySelector('#eco-count').textContent=`Item ${wasteIndex+1} of ${waste.length}`;}
document.querySelectorAll('[data-bin]').forEach(button=>button.onclick=()=>{const right=button.dataset.bin===waste[wasteIndex].b;if(right)wasteScore++;wasteIndex++;const msg=document.querySelector('#eco-message');if(wasteIndex<waste.length){msg.textContent=right?'Correct sorting!':'Not quite—try the next item.';renderWaste();}else{document.querySelector('#eco-item').textContent=`Score: ${wasteScore}/${waste.length}`;document.querySelector('#eco-emoji').textContent='🌍';document.querySelector('#eco-count').textContent='Challenge complete';msg.textContent='Small sorting choices create a cleaner world.';document.querySelector('#eco-restart').hidden=false;}});
document.querySelector('#eco-restart').onclick=()=>{wasteIndex=wasteScore=0;document.querySelector('#eco-restart').hidden=true;document.querySelector('#eco-message').textContent='';renderWaste();};renderWaste();

let seconds=1500, timerId=null; const timerText=document.querySelector('#timer'),toggle=document.querySelector('#timer-toggle'); function paintTimer(){timerText.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;} toggle.onclick=()=>{if(timerId){clearInterval(timerId);timerId=null;toggle.textContent='Start';}else{timerId=setInterval(()=>{seconds--;paintTimer();if(seconds<=0){clearInterval(timerId);timerId=null;toggle.textContent='Start';seconds=1500;alert('Focus session complete!');paintTimer();}},1000);toggle.textContent='Pause';}};document.querySelector('#timer-reset').onclick=()=>{clearInterval(timerId);timerId=null;seconds=1500;toggle.textContent='Start';paintTimer();};paintTimer();
const taskInput=document.querySelector('#task-input'),taskList=document.querySelector('#task-list');let tasks=JSON.parse(localStorage.getItem('focusflow-tasks')||'[]');function saveTasks(){localStorage.setItem('focusflow-tasks',JSON.stringify(tasks));}function renderTasks(){taskList.innerHTML='';tasks.forEach((task,i)=>{const li=document.createElement('li');li.className=task.done?'done':'';li.innerHTML=`<input type="checkbox" ${task.done?'checked':''}><span>${task.text}</span><button aria-label="Remove task">×</button>`;li.querySelector('input').onchange=()=>{tasks[i].done=!tasks[i].done;saveTasks();renderTasks();};li.querySelector('button').onclick=()=>{tasks.splice(i,1);saveTasks();renderTasks();};taskList.appendChild(li);});}function addTask(){const text=taskInput.value.trim();if(text){tasks.push({text,done:false});taskInput.value='';saveTasks();renderTasks();}}document.querySelector('#task-add').onclick=addTask;taskInput.onkeydown=e=>{if(e.key==='Enter')addTask();};renderTasks();
function gradeRow(){const row=document.createElement('div');row.className='grade-row';row.innerHTML='<input aria-label="Subject" placeholder="Subject"><input class="credit" aria-label="Credits" type="number" min="1" value="3"><input class="point" aria-label="Grade point" type="number" min="0" max="10" value="8">';document.querySelector('#grade-rows').appendChild(row);}document.querySelector('#add-grade').onclick=gradeRow;document.querySelector('#calculate-grade').onclick=()=>{let credits=0,total=0;document.querySelectorAll('.grade-row').forEach(row=>{const c=Number(row.querySelector('.credit').value),p=Number(row.querySelector('.point').value);if(c>0&&p>=0){credits+=c;total+=c*p;}});document.querySelector('#grade-result').textContent=credits?`SGPA: ${(total/credits).toFixed(2)}`:'Add valid credits and grade points.';};
